//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nomina
    {
        public int Id_Nomina { get; set; }
        public int Id_Vendedor { get; set; }
        public decimal Salario_Basico { get; set; }
        public Nullable<decimal> Auxilio_Transporte { get; set; }
        public Nullable<decimal> Auxilio_Alimentacion { get; set; }
        public int Id_Rango { get; set; }
        public System.DateTime Fecha_Nomina { get; set; }
        public Nullable<decimal> Valor_Sueldo { get; set; }
        public Nullable<decimal> SumaVentas { get; set; }
    
        public virtual Rango_venta Rango_venta { get; set; }
        public virtual Vendedor Vendedor { get; set; }
    }
}
