//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public int Id_Ventas { get; set; }
        public int Id_Vendedor { get; set; }
        public decimal Valor_Total_Ventas { get; set; }
        public int Cantidad_Vendida { get; set; }
        public decimal Valor_Producto { get; set; }
        public System.DateTime Fecha_venta { get; set; }
        public int Id_Producto { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual Vendedor Vendedor { get; set; }
    }
}
